name: Deploy
on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: Environment to deploy to
        required: true

jobs:
  greet:
    name: Greet in env ${{ inputs.environment }}
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest 
    steps:
      - name: step 1
        run: echo "WTF is this? ${{secrets.WTF}}"   
